### ISSUE TITLE
unexpected keyword argument 'disablejs'

### ISSUE THREAD

**Issue by karlch13** [thomasms/glastoselenium#10]
Got it working fine on my windows server now, but when running on my Mac with the updated version I now get this error: 

```
Karls-MacBook-Pro:glastoselenium-master Karl$ python3 scripts/glasto2020.py
Traceback (most recent call last):
  File "scripts/glasto2020.py", line 121, in <module>
    cache=cache, headless=headless, proxy=proxy)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/glasto/client.py", line 83, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'disablejs'
```

Any idea how to resolve this?

**Comment by thomasms** [comment]
What version of python are you using?
I.e
```bash
python3 --version
```

**Comment by thomasms** [comment]
Ah silly question I can see it in your error message. I will have a look with python 3.6 and get back to you.

**Comment by karlch13** [comment]
@thomasms  i've tried updating to python 3.7.4 and still running into the same issue

**Comment by karlch13** [comment]
I've fixed the issue, I re setup everything but this time used the "import glasto as gl" command instead of the pip3 install glasto

no idea why this fixed it though!

**Comment by thomasms** [comment]
The pip3 install version is not the latest. Once I am happy with the final one tonight/tomorrow it will be on Pypi. Until then if you need the bleeding edge just clone master!

**Comment by eddieod88** [comment]
On the subject of disablejs, is it wise to disable JS? Surely it will be used at some point in the card details entry point? If we disable it, surely that will mess things up?

**Comment by thomasms** [comment]
You are free to enable it. Just change the options to False :)
Remember this is a very hacky script that can only be tested 3 times a year for at most 30 mins at a time.
