### ISSUE TITLE
AttributeError: module 'glasto' has no attribute 'Twenty20'

### ISSUE THREAD

**Issue by andythornley** [thomasms/glastoselenium#12]
Hi, firstly thanks Thomas for all your hard work and making it available! 

Has anyone else had this error?   FYI this is on a Win10 machine, python 3.7

File ".\glasto2020.py", line 33, in <module>
    PHRASES_TO_CHECK = [gl.Twenty20.REGISTRATION_PHRASE]
AttributeError: module 'glasto' has no attribute 'Twenty20'

**Comment by andythornley** [comment]
Just tested with the glasto2019 script and that works ok, just checking changes.

**Comment by coolbotic** [comment]
@andythornley How did you set it in a windows machine as I was unable to get it running on mine?

**Comment by nicholaswhittle** [comment]
Delete the glasto folder/folders (might be multiple) in pip site-packages (you know the folders for this repo)
I had same problem, probably because you had installed it already

**Comment by andythornley** [comment]
Thanks for your help Nic, i removed the glasto folder from pip site-packages and everything is working!
