### ISSUE TITLE
Thanks so much!

### ISSUE THREAD

**Issue by karlch13** [thomasms/glastoselenium#16]
I got through and bought 6 with this then got through a second time but couldn't load the page after I clicked pay

**Comment by karlch13** [comment]
Thanks so much!

**Comment by thomasms** [comment]
Great, did the bot work? Did it automatically enter the reg details?
It worked for me again.

**Comment by karlch13** [comment]
Yep  took me straight through to the payment page, you're a legend!

**Comment by hasrya** [comment]
Hi karlch13 - congrats on getting the tickets.

I managed to get them too but just through the manual method.

Could you please let me know how you got this script to work?

I was getting an error when running the glasto2020.py script:

 "TypeError: __init__() got an unexpected keyword argument 'disablejs'"

I ended up running the 2019 script and just changing the URL but it never made it past the holding page.

**Comment by thomasms** [comment]
I think you needed the latest version of the package. I updated PyPi late Saturday evening. Always do:
```
pip3 install --upgrade glastoselenium
```
for the latest, otherwise clone from master and locally install.
