### ISSUE TITLE
Glasto 2020 registration phrase isn't on the reg page

### ISSUE THREAD

**Issue by asawhite** [thomasms/glastoselenium#2]
See https://www.glastonburyfestivals.co.uk/full-2020-ticket-info/

Might be helpful as they've included a screenshot of the 2020 reg page!

Also, any reason you're only allowing up to 4 reg details to be entered rather than the max of 6?

**Comment by thomasms** [comment]
Wow this is great, thank you for sharing. It's like they want us to try and automate it. I will incorporate these changes tonight (hopefully). 

Last year they only allowed 4, hence why 4, I will change this to 6 later.

**Comment by asawhite** [comment]
No problem, keep up the good work my guy 😁

**Comment by bhishp** [comment]
I think 4 is the April resale limit? If memory serves..

**Comment by thomasms** [comment]
Yes you are correct, that was why it was at 4.
