### ISSUE TITLE
Refreshes too fast

### ISSUE THREAD

**Issue by karlch13** [thomasms/glastoselenium#3]
Currently the script refreshes too quickly and ends up getting stuck on the limiting page.

**Comment by thomasms** [comment]
Which script is this for?
Have you tried changing the refresh rate? 

```python
c = gl.Twenty20(s, timeout=2, refreshrate=2)
```

**Comment by karlch13** [comment]
I was trying with the twenty20.py (I assume this will be updated once you've tested it on the coach ticket sales tonight) , I am an absolute beginner with coding but i'll try adjusting the refresh rate, also quick question which script do we need to update with the registration details and postcodes? 

Thanks so much for all the work you've put into this!

**Comment by thomasms** [comment]
The script glasto2020.py is my attempt for tonight, but it will most likely change after tonight.
```bash
python3 scripts/glasto2020.py
```

Try editing the script, you will see at the top that it has....
```python3
# first is lead booker
REG_DETAILS=[
    {
        'number': "123", 
        'postcode': "SW1 1AA"
    },
    {
        'number': "45", 
        'postcode': "SW1 1AB"
    },
    {
        'number': "67", 
        'postcode': "BA16 1AB"
    },
    {
        'number': "89", 
        'postcode': "BA12 2GB"
    }
]
```
change these to reflect your details.

But as said I added this for this year only, so I am not sure if it will work straight away. It works on the test site from last year, which can be found in the 'ref' folder. 

Try the script glastogo.py to test it with the old static site.
```bash
python3 scripts/glastogo.py
```

**Comment by karlch13** [comment]
Thanks for the help, I think I've got it working now, I'm not going for coach tickets so hopefully the changes after tonight will help!

**Comment by louisferraiolo** [comment]
@thomasms When running the `python3 scripts/glastogo.py` I just get redirected to the registration is closed page after it fills in all the details. Is that the expected behaviour?

**Comment by karlch13** [comment]
@louisferraiolo  I believe that means you've got it set up correctly as it uses the old static site.

**Comment by thomasms** [comment]
Yes, I never managed to save the html of the following page. But that means it works (for last year anyway).

**Comment by karlch13** [comment]
@thomasms  when running glasto2020.py now, it leads me to this page: https://glastonbury.seetickets.com/event/glastonbury-2020-deposits/worthy-farm/1300000 

saying event not found, it wasn't doing this earlier has something changed?

**Comment by thomasms** [comment]
Again, I am assuming that url will work for 2020 based on last year. They will activate the site at 18:00 (5 minutes) so until then we don't know.

**Comment by thomasms** [comment]
https://glastonbury.seetickets.com/event/glastonbury-2020-ticket-coach-travel-deposits/worthy-farm/1450012
