### ISSUE TITLE
Tour URL

### ISSUE THREAD

**Issue by andythornley** [thomasms/glastoselenium#5]
This seem to take you straight to the payment page: 

https://glastonbury.seetickets.com/tour/glastonbury-2020

**Comment by eddieod88** [comment]
Any luck people????

**Comment by karlch13** [comment]
Hopefully better luck on Sunday

**Comment by thomasms** [comment]
OK I will try that on Sunday. I got through via https://glastonbury.seetickets.com/event/glastonbury-2020-ticket-coach-travel-deposits/worthy-farm/1450012 but it then failed shortly afterward.
