### ISSUE TITLE
Issue at payment stage

### ISSUE THREAD

**Issue by asawhite** [thomasms/glastoselenium#6]
The tool worked really well and I got through! However, I got a timed out session error after putting in card details :(

See the error in terminal below, hope this helps:
<img width="491" alt="error" src="https://user-images.githubusercontent.com/1507401/66150198-8eb91100-e60c-11e9-8a72-05b339017796.png">

**Comment by thomasms** [comment]
OK, thanks for sharing. It seems my attempt to catch all the html caused it to crash. Simple solution is to wrap this with try except blocks.

**Comment by asawhite** [comment]
No problem. I've edited the script to wrap the tofile attempts in try except blocks. I'll try and do some testing tomorrow.

**Comment by asawhite** [comment]
Ok so quick update... I got tickets!

It said my session expired but I just got a booking confirmation. GG @thomasms you're a hero ❤

**Comment by karlch13** [comment]
Nice one!

**Comment by asawhite** [comment]
Closing as issue solved with latest commit

**Comment by karlch13** [comment]
@asawhite as you clearly know how to run this better than me, if I offered you some money for you if you managed to get my group tickets on Sunday (5 of us)?

**Comment by thomasms** [comment]
Congrats! I am glad it worked for you. I am adding some updates in order to make it better, so that it will work for more of you.

**Comment by karlch13** [comment]
@asawhite when running it did you leave everything as it was (refresh time)? Or did you edit any of the code?
