### ISSUE TITLE
Coach Result

### ISSUE THREAD

**Issue by bhishp** [thomasms/glastoselenium#7]
How did you fare...?

Didn't make it past the auto-refresh page 😑

**Comment by eddieod88** [comment]
> How did you fare...?
> 
> Didn't make it past the auto-refresh page 😑

same...

**Comment by asawhite** [comment]
Got through to card payment page but had a session expired message after even though I still had 3 mins left on the timer...

See my screenshot here: https://github.com/thomasms/glastoselenium/issues/6
