### ISSUE TITLE
SUNDAY PREPARATION

### ISSUE THREAD

**Issue by eddieod88** [thomasms/glastoselenium#8]
Right then. What needs to get sorted for sunday??

What is the exact url that needs to be entered? This will probably help us hit the ground running. My prediction is https://glastonbury.seetickets.com/event/glastonbury-2020-deposits/worthy-farm/1450010 

Not sure if we know this already though... the https://www.glastonburyfestivals.co.uk/full-2020-ticket-info/ has been temporarily disabled so can't check.

**Comment by asawhite** [comment]
You can use the wayback machine to see that page again, used it earlier

**Comment by thomasms** [comment]
Does wayback machine have the site for between time 18:00 and 18:27? It's quite sporadic in it's recording of sites.

I think that url is a good start. The numbers at the end are odd, I never understand how they decide on them. Last year it was 1300001.

**Comment by coolbotic** [comment]
Would it be worth adding threading and having a lot of web drivers all open at the same time to increase the chance?

**Comment by asawhite** [comment]
@thomasms unfortunately not but here is the link to the 2020 ticket info page: https://web.archive.org/web/20191002223316/https://www.glastonburyfestivals.co.uk/full-2020-ticket-info/

**Comment by coolbotic** [comment]
Ah, I was under the impression that each instance of a driver is like a separate device and most people that got tickets, say they used multiable devices on the same connection? If that is the case would the use of a proxy list for each instance of driver act as a completely new device, therefore more of a chance?

**Comment by thomasms** [comment]
Threading won't help here and python can't do threading properly anyway. I tried glastoswarm.py using multiprocessing lib but it can't handle more than 5 instances (not sure why).

Indeed, I agree, I think the best thing is to use a lot of proxies.

**Comment by Dirtyy** [comment]
<img width="1440" alt="Screenshot 2019-10-03 at 23 15 36" src="https://user-images.githubusercontent.com/7258738/66168050-ff275880-e633-11e9-9881-8e86bddca8a0.png">


Hey Guys, 

Here is a screenshot of the URL that was being used to get through to the coach tickets today. Hope this helps??

**Comment by scriptbunny245** [comment]
hi, @thomasms any idea on when you will be posting the full updated code?

**Comment by fukuokabernd** [comment]
Hi,
I was just playing around and seeing how fast i could refresh with the script when the current page started serving the rate limiting page (see attachment). Is this expected, even before the tickets go on sale, or might I have stumbled upon an anti scripting measure?
![Glast](https://user-images.githubusercontent.com/1869195/66257329-fbace200-e797-11e9-9287-a38c74e03571.PNG)

**Comment by thomasms** [comment]
Indeed I've noticed this today, maybe the days of this script are over.
Try a higher refresh rate.
I advise the use of VPNs to avoid getting blocked.

**Comment by thomasms** [comment]
@scriptbunny245 I haven't had any opportunity to work on this today. I will have to do it tonight.
I have a few other ideas to try before tomorrow.

**Comment by ghost** [comment]
The hit limit is currently 60 per minute before you get the limiting page. It does time out after the minute is up though.

There's no way to test whether it's the same on Sunday as the real holding page looks identical.

**Comment by fukuokabernd** [comment]
The limit is bound to the X-Mapping-kgibjjhc cookie, not the IP (or probably it is hold by the load balancing server which might change when you delete this cookie). Maybe we could just restart the browser or flush the cookies every ~~minute~~ 60 refreshs.

**Comment by fukuokabernd** [comment]
I have experimented a bit more, the limit seems to be per load balancer and IP. A single browser with 1 request per second works fine, if you start more at some point two of them will get the hit limit (so it seems they ended up on the same server). No idea how to find out on which server you end up though.
So the best/safest would be to use many different IPs with one request per second each.

**Comment by BurhanBashir2019** [comment]
Hey Guys, I am looking to open about 50 sessions. Does anyone here plan on opening multiple sessions, if so would you mind sharing your approach?

**Comment by ghost** [comment]
> The hit limit is currently 60 per minute before you get the limiting page. It does time out after the minute is up though.
> 
> There's no way to test whether it's the same on Sunday as the real holding page looks identical.

Would it be possible to have a list of proxies to exchuast as fast as possible then switch after 60 requests have been made maybe?

**Comment by thomasms** [comment]
I've had limited time today (very busy with life). I have only had 30 minutes tonight to add some new "features".

I've added a scout script which aims to figure out possible URLs in a headless manner (hopefully a bit quicker). Some small refactoring but largely script is unchanged. It is impossible to know what will happen tomorrow but we will see. Good luck to all.

**Comment by BurhanBashir2019** [comment]
I run glastogo.py and it enters the details and takes me to event not found, is this expected behavior?

**Comment by thomasms** [comment]
That is the test script for last years static site. Use glasto2020.py.
