### ISSUE TITLE
how to set selenium driver path if running in windows

### ISSUE THREAD

**Issue by karlch13** [thomasms/glastoselenium#9]
Then set the path to the driver via:

export CHROMEDRIVER=/path/to/chromedriver

works fine on mac OS however I cant get this to work on windows

**Comment by asawhite** [comment]
Paste the following into cmd:
set C:\your\path\to\chromedriver.exe

This will set the variable for the current cmd session

**Comment by asawhite** [comment]
Set that first then run python3 scripts/glasto20.py

**Comment by thomasms** [comment]
Indeed, @asawhite is correct. Use 'set' instead of 'export' on windows and remember backslashes not forward slashes for windows.

Apologies, this has all been assuming users are Linux or Mac based, and using chrome. This needs adding to the README.

**Comment by thehodown** [comment]
> Paste the following into cmd:
> set C:\your\path\to\chromedriver.exe
> 
> This will set the variable for the current cmd session

You need to specify the variable you're setting ;) So, it's actually:

set CHROMEDRIVER=C:\your\path\to\chromedriver.exe

**Comment by asawhite** [comment]
My bad! Had a few too many last night in celebration 😉

**Comment by karlch13** [comment]
thanks, i'm setting it up on a windows server I've got so i'm even less familiar with that!

**Comment by karlch13** [comment]
@asawhite when you had success running on thursday did you change the refresh speed or leave it as it is in the github file?

**Comment by asawhite** [comment]
@karlch13 I left refresh rate as is, seemed to be ok for me.

Not sure if it's been updated yet but might need to change the registration phrase in twenty20.py to something that's definitely on the page. See the following page: https://web.archive.org/web/20191002223316/https://www.glastonburyfestivals.co.uk/full-2020-ticket-info/

**Comment by karlch13** [comment]
got it working fine on windows now but on my mac with the updated version I now get this error: 

K```
arls-MacBook-Pro:glastoselenium-master Karl$ python3 scripts/glasto2020.py
Traceback (most recent call last):
  File "scripts/glasto2020.py", line 121, in <module>
    cache=cache, headless=headless, proxy=proxy)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/glasto/client.py", line 83, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'disablejs'
```
